# Enable pre-loading of vocabularies into Redis
# Called by rake sifd:load_vocabs to be used on new deploys only.
workflow_status:
  name: Workflow status
  entries:
    - Ingested
    - Metadata complete
    - Færdig forvaltet
title_types:
  name: Title types
  entries:
    - Uniform
    - Abbreviated
    - Translated
    - Alternative
language:
  name: Language
  entries:
    - dan
    - eng
    - sve