development:
  user: <%= CONFIG[:development][:fedora_user] %>
  password: <%= CONFIG[:development][:fedora_passwd] %>
  url: <%= CONFIG[:development][:fedora_url] %>
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
production:
  user: <%= CONFIG[:production][:fedora_user] %>
  password: <%= CONFIG[:production][:fedora_passwd] %>
  url: <%= CONFIG[:production][:fedora_url] %>
cucumber:
  <<: *TEST
