development:
  host: 'thor.kb.dk'
  port: 389
  attribute: sAMAccountName
  base: 'OU=KB,DC=kb,DC=dk'
  admin_user: <%= CONFIG[:ldap][:user] %>
  admin_password: <%= CONFIG[:ldap][:password] %>
  ssl: false
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: localhost
  port: 636
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: start_tls
  # <<: *AUTHORIZATIONS