development:
  mq_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-dev-queue"
    response: "preservation-dev-response-queue"
    polling_interval_in_minutes: 1

test:
  mq_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-test-queue"
    response: "preservation-test-response-queue"
    polling_interval_in_minutes: 1

production:
  mq_uri: "amqp://sifd-staging-03:5672"
  preservation:
    destination: "preservation-prod-queue"
    response: "preservation-prod-response-queue"
    polling_interval_in_minutes: 1
