local-development:
  snippet_server_url: http://localhost:8080/exist/rest/db/letter_books
  snippet_server_url_with_admin: http://admin@localhost:8080/exist/rest/db/letter_books
  snippet_server_user: admin
  snippet_server_password: flormelis
  get_snippet_script: present.xq
  image_server_prefix: http://kb-images.kb.dk/public/dk_breve/
  feedback_mail: fejlrapportering@adl.dk
development:
  snippet_server_url: http://valhal-test-01.kb.dk:8080/exist/rest/db/letter_books
  snippet_server_url_with_admin: http://admin@valhal-test-01.kb.dk:8080/exist/rest/db/letter_books
  snippet_server_user: admin
  snippet_server_password: admin1234
  get_snippet_script: present.xq
  image_server_prefix: http://kb-images.kb.dk/public/dk_breve/
  feedback_mail: fejlrapportering@adl.dk
test:
  snippet_server_url: http://bifrost-test-01.kb.dk:8080/exist/rest/db/letter_books
  get_snippet_script: present.xq
  image_server_prefix: http://kb-images.kb.dk/public/
  feedback_mail: fejlrapportering@adl.dk
production:
  snippet_server_url: http://valhal-test-01.kb.dk:8080/exist/rest/db/letter_books
  snippet_server_url_with_admin: http://admin@valhal-test-01.kb.dk:8080/exist/rest/db/letter_books
  snippet_server_user: admin
  snippet_server_password: admin1234
  get_snippet_script: present.xq
  image_server_prefix: http://kb-images.kb.dk/public/dk_breve/
  feedback_mail: fejlrapportering@adl.dk

