development:
  snippet_server_url: http://bifrost-test-01:8080/exist/rest/db/
  get_snippet_script: present.xq
  image_server_prefix: http://kb-images.kb.dk/public/
  feedback_mail: fejlrapportering@adl.dk
test:
  snippet_server_url: http://bifrost-test-01:8080/exist/rest/db/letter_books/
  get_snippet_script: present.xq
  image_server_prefix: http://kb-images.kb.dk/public/
  feedback_mail: fejlrapportering@adl.dk
production:
  snippet_server_url: http://bifrost-test-01:8080/exist/rest/db/
  get_snippet_script: present.xq
  image_server_prefix: http://kb-images.kb.dk/public/
  feedback_mail: fejlrapportering@adl.dk
